const admin_menu = [
  { 'p': '/', 'template': 'dashboard' },
  { 'p': 'dashboard', 'template': 'dashboard' },
  { 'p': 'booking-report', 'template': 'booking_report' },
  { 'p': 'cancel-booking', 'template': 'cancel_booking' },
  { 'p': 'config-building', 'template': 'config_building' },
  { 'p': 'building-edit', 'template': 'config_building_edit' },
  { 'p': 'room-insert', 'template': 'room_insert' },
  { 'p': 'room-edit', 'template': 'room_edit' },
  { 'p': 'room-manage', 'template': 'room_manage' },
  { 'p': 'price-manage', 'template': 'price_manage' },
  { 'p': 'price-insert', 'template': 'price_insert' },
  { 'p': 'price-edit', 'template': 'price_edit' },
  { 'p': 'manage-slide', 'template': 'manage_slide' },
  { 'p': 'checkout', 'template': 'room_checkout' },
  { 'p': 'resting', 'template': 'room_resting' },
  { 'p': 'list-room', 'template': 'list_room' },
  { 'p': 'booking-room', 'template': 'booking_room' },
  { 'p': 'payment', 'template': 'payment' },
  { 'p': 'qrcode', 'template': 'qrcode' },
  { 'p': 'social-contact', 'template': 'social_contact' },
  { 'p': 'facility', 'template': 'facility' },
  { 'p': 'add-facility', 'template': 'facility_insert' },
  { 'p': 'facility-edit', 'template': 'facility_edit' },
  { 'p': 'web-about', 'template': 'web_about' },
  { 'p': 'mlogo', 'template': 'mlogo' },
  { 'p': 'kword', 'template': 'kword' },
  { 'p': 'user-admin', 'template': 'user_admin' },
  { 'p': 'admin-insert', 'template': 'user_admin_insert' },
  { 'p': 'admin-edit', 'template': 'user_admin_edit' },
  { 'p': 'room-about', 'template': 'room_about' },
]
module.exports.admin_menu = admin_menu